src/myfinance-web-dotnet/Models/ErrorViewModel.cs
namespace myfinance_web_dotnet.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

src/myfinance-web-dotnet/Models/PlanoContaModel.cs
namespace myfinance_web_dotnet.Domain;

public class PlanoContaModel
{
    public int? Id { get; set; }
    public string Nome { get; set; }
    public string Tipo { get; set; } // "Receita" ou "Despesa"
}

src/myfinance-web-dotnet/Models/TransacaoModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using myfinance_web_dotnet.Services;

namespace myfinance_web_dotnet.Domain;

public class TransacaoModel
{
    public TransacaoModel(iRepository<PlanoConta> _PlanoContaRepository)
    {
        var listaPlanoConta = _PlanoContaRepository.ListarRegistros();
        PlanoConta = new SelectList(listaPlanoConta, "Id", "Nome");

        Data = DateTime.Now;
    }
    public int? Id { get; set; }
    public string? Historico { get; set; }
    public string? Tipo { get; set; }
    public DateTime Data { get; set; }
    public int PlanoContaId { get; set; }
    public IEnumerable<SelectListItem>? PlanoConta { get; set; }
    public decimal Valor { get; set; }
}

src/myfinance-web-dotnet/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using myfinance_web_dotnet.Infrastructure;
using myfinance_web_dotnet.Models;

namespace myfinance_web_dotnet.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;
    private readonly MyFinanceDbContext _banco;

    public HomeController(ILogger<HomeController> logger, MyFinanceDbContext banco)
    {
        _logger = logger;
        _banco = banco;
    }

    public IActionResult Index()
    {
        var nomePrimeiroItemPlanoConta = _banco.PlanoConta.FirstOrDefault().Nome;
        ViewBag.Teste = nomePrimeiroItemPlanoConta;
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

src/myfinance-web-dotnet/Controllers/PlanoContaController.cs
using Microsoft.AspNetCore.Mvc;
using myfinance_web_dotnet.Domain;
using myfinance_web_dotnet.Infrastructure;
using myfinance_web_dotnet.Services;

namespace myfinance_web_dotnet.Controllers;

[Route("[controller]")]
public class PlanoContaController : Controller
{
    private readonly ILogger<PlanoContaController> _logger;
    private readonly iRepository<PlanoConta> _PlanoContaRepository;

    public PlanoContaController(
        ILogger<PlanoContaController> logger,
        iRepository<PlanoConta> PlanoContaService)
    {
        _logger = logger;
        _PlanoContaRepository = PlanoContaService;
    }

    [Route("Index")]
    public IActionResult Index()
    {
        ViewBag.Lista = _PlanoContaRepository.ListarRegistros();
        return View();
    }

    [HttpPost]
    [HttpGet]

    [Route("Cadastro")]
    [Route("Cadastro/{id}")]
    public IActionResult Cadastro(PlanoContaModel? model, int? id)
    {
        if (id != null && !ModelState.IsValid) //Carregar o registro em tela
        {
            var registro = _PlanoContaRepository.RetornarRegistro((int)id);

            var planoContaModel = new PlanoContaModel()
            {
                Id = registro.Id,
                Nome = registro.Nome,
                Tipo = registro.Tipo
            };

            return View(planoContaModel);
        }
        else if (model != null && ModelState.IsValid)
        {
            var planoConta = new PlanoConta
            {
                Id = model.Id,
                Nome = model.Nome,
                Tipo = model.Tipo
            };

            _PlanoContaRepository.Salvar(planoConta);

            return RedirectToAction("Index");
        }
        else
        {
            return View();
        }
    }

    [HttpGet]
    [Route("Excluir/{id}")]
    public IActionResult Excluir(int id)
    {
        _PlanoContaRepository.Excluir(id);
        return RedirectToAction("Index");
    }
}

src/myfinance-web-dotnet/Controllers/TransacaoController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using myfinance_web_dotnet.Domain;
using myfinance_web_dotnet.Infrastructure;
using myfinance_web_dotnet.Services;

namespace myfinance_web_dotnet.Controllers;

[Route("[controller]")]
public class TransacaoController : Controller
{
    private readonly ILogger<TransacaoController> _logger;
    private readonly iRepository<PlanoConta> _PlanoContaRepository;
    private readonly iRepository<Transacao> _TransacaoRepository;

    public TransacaoController(
        ILogger<TransacaoController> logger,
        iRepository<PlanoConta> PlanoContaRepository,
        iRepository<Transacao> TransacaoRepository)
    {
        _logger = logger;
        _PlanoContaRepository = PlanoContaRepository;
        _TransacaoRepository = TransacaoRepository;
    }

    [Route("Index")]
    public IActionResult Index()
    {
        ViewBag.Lista = _TransacaoRepository.ListarRegistros();
        return View();
    }

    [HttpGet("Cadastro")]
    public IActionResult Cadastro()
    {
        var transacaoModel = new TransacaoModel(_PlanoContaRepository);
        return View(transacaoModel);        
    }

    [HttpGet("Cadastro/{id}")]
    public IActionResult Cadastro(int id)
    {
        var registro = _TransacaoRepository.RetornarRegistro(id);

        var transacaoModel = new TransacaoModel(_PlanoContaRepository)
        {
            Id = registro.Id,
            Historico = registro.Historico,
            Tipo = registro.PlanoConta.Tipo,
            Data = registro.Data,
            Valor = registro.Valor,
            PlanoContaId = registro.PlanoContaId,
        };

        return View(transacaoModel);
    }


    [HttpPost("Cadastro")]
    [HttpPost("Cadastro/{id}")]
    public IActionResult Cadastro(TransacaoModel? model, int? id)
    {
        if (ModelState.IsValid)
        {
            var transacao = new Transacao
            {
                Id = model.Id,
                Historico = model.Historico,
                Data = model.Data,
                Valor = model.Valor,
                PlanoContaId = model.PlanoContaId
            };

            _TransacaoRepository.Salvar(transacao);
        }
        
        return RedirectToAction("Index");
    }

    [HttpGet]
    [Route("Excluir/{id}")]
    public IActionResult Excluir(int id)
    {
        _TransacaoRepository.Excluir(id);
        return RedirectToAction("Index");
    }
}

src/myfinance-web-dotnet/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome: @ViewBag.Teste</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

src/myfinance-web-dotnet/Views/PlanoConta/Cadastro.cshtml
@using myfinance_web_dotnet.Domain
@model PlanoContaModel

@{
    ViewData["Title"] = "Cadastro de Plano de Contas";
}

<h1>@ViewData["Title"]</h1>

<form asp-controller="PlanoConta" asp-action="Cadastro" method="post">
    <div class="container">
        <div class="mb-3">
            <label class="form-label">Descrição</label>
            <input type="hidden" id="txtId" class="form-control" asp-for="Id" />
            <input type="text" id="txtNome" class="form-control" asp-for="Nome" />
            <span asp-validation-for="Nome" class="text-danger"></span>
        </div>

        <div class="mb-3">
            <label>@Html.RadioButtonFor(m => m.Tipo, "D")Despesa</label>
            <label>@Html.RadioButtonFor(m => m.Tipo, "R")Receita</label>
            <span asp-validation-for="Tipo" class="text-danger"></span>
        </div>

        <div class="mb-3">
            <button type="submit" class="btn btn-primary btn-lg">Salvar</button>
            <button type="button" class="btn btn-secondary btn-lg" onclick="Voltar()">Cancelar</button>
        </div>
    </div>
</form>

<script>
    function Voltar() {
        window.location.href = "/PlanoConta/Index";
    }
</script>

src/myfinance-web-dotnet/Views/PlanoConta/Index.cshtml
@using myfinance_web_dotnet.Domain
<h1>Plano de Contas </h1>

<br /> 

<a asp-controller="PlanoConta" asp-action="Cadastro" class="btn btn-success">Criar item de plano de conta</a>

<br /><br /> 

<table class="table table-striped">
        <tr>
            <th>Id</th>
            <th>Descrição</th>
            <th>Tipo</th>
            <th>#</th>
            <th>#</th>
        </tr>

        @{
            foreach (var item in (List<PlanoConta>)ViewBag.Lista)
            {
                <tr>
                    <td>@item.Id</td>
                    <td>@item.Nome</td>
                    <td>@item.Tipo</td>
                    <td><button type="button" class="btn btn-warning" onclick="Editar(@item.Id)">Editar</button></td>
                    <td><button type="button" class="btn btn-danger" onclick="Excluir(@item.Id)">Excluir</button></td>
                </tr>
            }
        }
    </table>

    <script>
        function Excluir(id) {
            if (confirm("Deseja realmente excluir?")) {
                window.location.href = "/PlanoConta/Excluir/" + id;
            }
        }

        function Editar(id) {
            window.location.href = "/PlanoConta/Cadastro/" + id;
        }
    </script>

src/myfinance-web-dotnet/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - myfinance_web_dotnet</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/myfinance_web_dotnet.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">myfinance_web_dotnet</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="PlanoConta" asp-action="Index">Plano de Contas</a>
                        </li>
                        <li class="nav-item"></li>
                            <a class="nav-link text-dark" asp-area="" asp-controller="Transacao" asp-action="Index">Registro de Transações</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - myfinance_web_dotnet - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

src/myfinance-web-dotnet/Views/Transacao/Cadastro.cshtml
@using myfinance_web_dotnet.Domain

@model TransacaoModel

@{
    ViewData["Title"] = "Registro de Transações";
}

<h1>@ViewData["Title"]</h1>

<form asp-controller="Transacao" asp-action="Cadastro" method="post">
    <div class="container">
        <div class="mb-3">
            <label class="form-label">Data</label>
            <input type="date" id="txtData" class="form-control" asp-for="Data" />
        </div>

        <div class="mb-3">
            <label class="form-label">Valor</label>
            <input type="number" id="txtValor" class="form-control" asp-for="Valor" />
        </div>

        <div class="mb-3">
            <label class="form-label">Item Plano Conta</label>
            @Html.DropDownListFor(m => m.PlanoContaId, Model.PlanoConta, new { @class = "form-select" })
        </div>

        <div class="mb-3">
            <label class="form-label">Histórico</label>
            <input type="hidden" id="txtId" class="form-control" asp-for="Id" />
            <input type="text" id="txtNome" class="form-control" asp-for="Historico" />
        </div>

        <div class="mb-3">
            <button type="submit" class="btn btn-primary btn-lg">Salvar</button>
            <button type="button" class="btn btn-secondary btn-lg" onclick="Voltar()">Cancelar</button>
        </div>
    </div>
</form>


<script>
    function Voltar() {
        window.location.href = "/Transacao/Index";
    }
</script>

src/myfinance-web-dotnet/Views/Transacao/Index.cshtml
@using myfinance_web_dotnet.Domain
<h1>Listagem de Transações Financeiras</h1>

<br /> 

<a asp-controller="Transacao" asp-action="Cadastro" class="btn btn-success">Registrar uma transação</a>

<br /><br /> 

<table class="table table-striped">
        <tr>
            <th>Id</th>
            <th>Histórico</th>
            <th>Tipo</th>
            <th>Valor</th>
            <th>Data</th>
            <th>#</th>
            <th>#</th>
        </tr>

        @{
            foreach (var item in (List<Transacao>)ViewBag.Lista)
            {
                <tr>
                    <td>@item.Id</td>
                    <td>@item.Historico</td>
                    <td>@item.PlanoConta.Tipo</td>
                    <td>@item.Valor</td>
                    <td>@item.Data</td>
                    <td><button type="button" class="btn btn-warning" onclick="Editar(@item.Id)">Editar</button></td>
                    <td><button type="button" class="btn btn-danger" onclick="Excluir(@item.Id)">Excluir</button></td>
                </tr>
            }
        }
    </table>

    <script>
        function Excluir(id) {
            if (confirm("Deseja realmente excluir?")) {
                window.location.href = "/Transacao/Excluir/" + id;
            }
        }

        function Editar(id) {
            window.location.href = "/Transacao/Cadastro/" + id;
        }
    </script>